import type { StatusReport } from "@/modules/reports/status-report";

/** A report with everything in it, shaped like the demo project on a yellow week. */
export function fullReport(): StatusReport {
  return {
    version: 2,
    today: "2026-09-04",
    weekKey: "2026-W36",
    projectName: "Forårskonference",
    goal: "100 tilmeldte og et program på plads seks uger før",
    ownerName: "Lise Holm",
    managerName: "Mette Krag",
    approvedByName: "Mette Krag",
    rag: "yellow",
    ragSuggested: "yellow",
    ragReason:
      "Næste milepæl er om 18 dage med 2 åbne opgaver, og noget er allerede forsinket. Der er én åben forhindring.",
    text: 'Programarbejdet er på sporet: tema og spor er fastlagt, og tre af fem oplægsholdere har bekræftet. Milepælen "Lokale og dato låst" den 22. september holder kun, hvis det store lokale bekræftes i denne uge. Tilmeldingssiden er forsinket fire dage. Der er brugt 75 % af budgettet mod 44 % af opgaverne, primært fordi lokaleforskud og honorarer er forudbetalt.',
    managerComment:
      "Jeg er ikke bekymret for programmet, men for lokalet. Hvis vi ikke får en beslutning i denne uge, anbefaler jeg det mindre lokale frem for at flytte datoen.",
    managementAsks: [
      {
        id: "a1",
        text: "Godkend, at vi binder os til det store lokale nu",
        dueDate: "2026-09-10",
        carriedFrom: null,
        answered: false,
      },
      {
        id: "a2",
        text: "Frigiv kommunikationsafdelingen to dage i uge 38",
        dueDate: "2026-09-15",
        carriedFrom: "2026-W35",
        answered: false,
      },
    ],
    nextWeek: [
      "Bekræfte lokale eller vælge alternativet (Mette)",
      "To sidste oplægsholdere på plads (Jonas)",
      "Tilmeldingsside klar til test (Sofie)",
    ],
    sinceLast: [
      "3 opgaver afsluttet, blandt andet „Fastlæg tema og spor“",
      "„Byg tilmeldingsside“ blev flyttet",
      "Ny forhindring: „Det store lokale er muligvis optaget i uge 43“",
      "Beslutning: Keynote bliver Anna Skov",
    ],
    trend: [
      { weekKey: "2026-W32", rag: "green" },
      { weekKey: "2026-W33", rag: "green" },
      { weekKey: "2026-W34", rag: "green" },
      { weekKey: "2026-W35", rag: "yellow" },
      { weekKey: "2026-W36", rag: "yellow" },
    ],
    progress: { done: 4, total: 9 },
    economy: { budget: 60000, plannedTotal: 53000, incurredTotal: 45000, postCount: 4 },
    expenses: [
      { title: "Lokaleleje, forskud", amount: 25000, incurred: true },
      { title: "Oplægsholdere, honorarer", amount: 20000, incurred: true },
      { title: "Forplejning", amount: 8000, incurred: false },
    ],
    milestones: [
      {
        title: "Lokale og dato låst",
        date: "2026-09-22",
        done: false,
        ownerName: "Mette",
        criterion: "",
      },
      {
        title: "Program offentliggjort",
        date: "2026-10-20",
        done: false,
        ownerName: "Jonas",
        criterion: "",
      },
      {
        title: "Konference afholdt",
        date: "2026-12-01",
        done: false,
        ownerName: "Lise",
        criterion: "",
      },
    ],
    tasks: [
      {
        title: "Indhent tilbud på tre lokaler",
        start: "2026-08-18",
        end: "2026-08-28",
        state: "done",
        owner: "Mette",
        participants: 0,
        milestoneIndex: 0,
      },
      {
        title: "Vælg lokale og book",
        start: "2026-08-29",
        end: "2026-09-12",
        state: "doing",
        owner: "Mette",
        participants: 0,
        milestoneIndex: 0,
      },
      {
        title: "Fastlæg tema og spor",
        start: "2026-08-25",
        end: "2026-09-03",
        state: "done",
        owner: "Jonas",
        participants: 0,
        milestoneIndex: 1,
      },
      {
        title: "Kontakt og bekræft oplægsholdere",
        start: "2026-09-04",
        end: "2026-10-02",
        state: "doing",
        owner: "Jonas",
        participants: 2,
        milestoneIndex: 1,
      },
      {
        title: "Byg tilmeldingsside",
        start: "2026-08-20",
        end: "2026-08-31",
        state: "doing",
        owner: "Sofie",
        participants: 0,
        milestoneIndex: 1,
      },
      {
        title: "Tilmeldingskampagne",
        start: "2026-09-22",
        end: "2026-10-13",
        state: "todo",
        owner: "Sofie",
        participants: 0,
        milestoneIndex: 1,
      },
      {
        title: "Bestil forplejning",
        start: "2026-11-02",
        end: "2026-11-10",
        state: "todo",
        owner: "Mette",
        participants: 0,
        milestoneIndex: 2,
      },
      {
        title: "Print og skilte",
        start: "2026-11-16",
        end: "2026-11-25",
        state: "todo",
        owner: "Sofie",
        participants: 0,
        milestoneIndex: 2,
      },
      {
        title: "Afvikling",
        start: "2026-12-01",
        end: "2026-12-01",
        state: "todo",
        owner: "Lise",
        participants: 3,
        milestoneIndex: 2,
      },
    ],
    obstacles: [{ title: "Det store lokale er muligvis optaget i uge 43", since: "2026-08-28" }],
    decisions: [
      { title: "Keynote bliver Anna Skov", note: "honorar 12.000 kr.", date: "2026-09-01" },
      { title: "Programmet får tre spor, ikke fire", note: "", date: "2026-08-28" },
    ],
    decisionsSince: "2026-W35",
    engine: "mistral",
  };
}
